FILTER_ATTRIBUTES = {
 "1065": {"aggrType": "terms", "filterType": "buckets", "appliedCategories": [1410]},
 "16803": {"aggrType": "terms", "filterType": "buckets", "appliedCategories": [1410]},
 "1860": {"aggrType": "terms", "filterType": "buckets", "appliedCategories": [1410]},
 "1866": {"aggrType": "terms", "filterType": "buckets", "appliedCategories": [1410]},
 "1923": {"aggrType": "terms", "filterType": "buckets", "appliedCategories": [1410]},
 "788": {"aggrType": "terms", "filterType": "buckets", "appliedCategories": [1410]},
 "7454": {"aggrType": "terms", "filterType": "buckets", "appliedCategories": [1410]},
 "7416": {"aggrType": "range", "filterType": "buckets", "appliedCategories": [1410]},
 "338": {"aggrType": "terms", "filterType": "buckets", "appliedCategories": [1410]},
 "661": {"aggrType": "terms", "filterType": "buckets", "appliedCategories": [1410]},
 "41": {"aggrType": "terms", "filterType": "buckets", "appliedCategories": [1083]},
 "54": {"aggrType": "range", "filterType": "buckets", "appliedCategories": [1083]},
 "253": {"aggrType": "terms", "filterType": "buckets", "appliedCategories": [1083]},
 "315": {"aggrType": "terms", "filterType": "buckets", "appliedCategories": [1083]},
 "4534": {"aggrType": "terms", "filterType": "buckets", "appliedCategories": [1083]},
 "5294": {"aggrType": "terms", "filterType": "buckets", "appliedCategories": [1083]},
 "11044": {"aggrType": "terms", "filterType": "buckets", "appliedCategories": [1083]},
 "15660": {"aggrType": "terms", "filterType": "buckets", "appliedCategories": [1083]},
 "16546": {"aggrType": "terms", "filterType": "buckets", "appliedCategories": [1083]},
 "26676": {"aggrType": "terms", "filterType": "buckets", "appliedCategories": [1083]},
 "6373": {"aggrType": "terms", "filterType": "buckets", "appliedCategories": [54]},
 "7471": {"aggrType": "terms", "filterType": "buckets", "appliedCategories": [54]},
 "8654": {"aggrType": "terms", "filterType": "buckets", "appliedCategories": [54]},
 "14299": {"aggrType": "terms", "filterType": "buckets", "appliedCategories": [54]}
}